#здесь прописываются все глобальные настройки внутри приложения
"""
Django settings for StudentsLife project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#секретный ключ никому не показывать, перед выгрузкой на сервер можно изменить и даже лучше
SECRET_KEY = 'django-insecure-iap#70r7gl#e)q&=*vp5ipuzx_d0uuw!t*pf^&vy%-3s@h9d2c'

# SECURITY WARNING: don't run with debug turned on in production!
#означает что все ошибки будут отображаться на самом сайте. При выгрузке поменять на False
DEBUG = True

#указываем доменные имена на которые можем опубликовать проект
#если хотим чтобы был сайт на хосте https://itproger.com, то в кавычках в список так и указываем
ALLOWED_HOSTS = []


# Application definition
#набор всез установленных прилдений, которые есть в проекте. Можно и свои прописывать
INSTALLED_APPS = [
    'django.contrib.admin', #панель администратора
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'news',
    'university'
]

#различные промежуточное по, например те классы, плагины библиотеки
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', #обеспечивают безопасность
    'django.contrib.sessions.middleware.SessionMiddleware', #обеспечивают работу с сессиями внутри проекта
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', #Csrf - токен
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'StudentsLife.urls' #указан основной файл урлс

#указывается какие шаблоны мы можем использовать внутри нашего проекта
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#где находится wsgi чтобы мы потом могли выгрузить на сервер
WSGI_APPLICATION = 'StudentsLife.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#указывается база данных с которой мы работаем По умолчанию sqlite3
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    #"/var/www/static/", #вроде как нужен только когда на сервер загружаем
]
